.debs_template: &debs
  stage: test
  when: manual
  parallel:
    matrix:
      - PACKAGE: ["doc","domserver","judgehost"]
  script:
    - apt update; apt install -y curl gnupg apt-transport-https
    - curl -o - https://www.domjudge.org/repokey.asc | apt-key add -
    - echo "deb     https://domjudge.org/debian unstable/" >> /etc/apt/sources.list.d/domjudge.list
    - apt update; apt install -y domjudge-"$PACKAGE"
    - apt list domjudge*

debian-debs-stab:
  <<: *debs
  image: debian:stable

debian-debs-oldstab:
  <<: *debs
  image: debian:oldstable

ubuntu-debs-latest:
  <<: *debs
  image: ubuntu:latest

ubuntu-debs-rolling:
  <<: *debs
  image: ubuntu:rolling

