.debs_template: &debs
  stage: test
  when: manual
  parallel:
    matrix:
      - PACKAGE: ["doc","domserver","judgehost"]
  script:
    - curl -o - https://www.domjudge.org/repokey.asc | sudo apt-key add -
    - echo "deb     https://domjudge.org/debian unstable/" >> /etc/apt/sources.list.d/tmp
    - apt update; apt install domserver-"$PACKAGE"
    - apt list domjudge*

debian-debs-stab:
  <<: *debs
  image: debian/stable

debian-debs-oldstab:
  <<: *debs
  image: debian/oldstable

ubuntu-debs-latest:
  <<: *debs
  image: ubuntu/latest

ubuntu-debs-rolling:
  <<: *debs
  image: debian/rolling

