# The jobs to do a manual DOMjudge release
createtar:
  stage: test
  when: manual
  image: domjudge/gitlabci:2.1
  script:
    - echo -e "\e[0Ksection_start:`date +%s`:buildrelease\r\e[0KBuild of release tarball"
    - wget https://raw.githubusercontent.com/DOMjudge/domjudge-scripts/main/make_release.sh
    - sh ./make_release.sh $DOMJUDGE_VERSION
    - echo -e "\e[0Ksection_end:`date +%s`:buildrelease\r\e[0K"
    - echo -e "\e[0Ksection_start:`date +%s`:aptpackages\r\e[0KInstall the expected packages for new release"
    - apt update
    - apt install -y acl zip unzip mariadb-server apache2 php php-fpm php-gd php-cli php-intl php-mbstring php-mysql php-curl php-json php-xml php-zip composer ntp
    - apt install -y make pkg-config sudo debootstrap libcgroup-dev php-cli php-curl php-json php-xml php-zip lsof procps
    - echo -e "\e[0Ksection_end:`date +%s`:aptpackages\r\e[0K"
    - echo -e "\e[0Ksection_start:`date +%s`:testtar\r\e[0KTest the release tarball"
    - tar zxvf domjudge-${DOMJUDGE_VERSION}.tar.gz
    - cd domjudge-${DOMJUDGE_VERSION}
    - ./configure
    - make build
    - make clean
    - make all
    - make clean
    - make docs
    - make clean
    - make submitclient
    - echo -e "\e[0Ksection_end:`date +%s`:testtar\r\e[0K"
    - echo "See the new_release_howto.txt (L28/domjudge-scripts) for the next step."

