#!/bin/sh
set -e

# This file adds DOMjudge specific versions of the first linux menuentry.

LINUX="$(dirname "$0")/10_linux"

make_entry()
{
	TARGET="$1"
	NAME="$2"
	shift 2
	$LINUX | sed -n '/^ *menuentry /,/^ *}/ p' | \
	sed -e 's/\(linux.* root=.*\)/\1'" systemd.unit=$TARGET.target $*/" \
	    -e "s/^\( *menuentry\) '[^']*'/\1 '$NAME'/"
}

make_entry domjudge-all 'DOMjudge domserver \& judgehost'
make_entry domserver    'DOMjudge domserver'
make_entry judgehost    'DOMjudge judgehost'
