name: Detect changed files

inputs:
  trigger-files:
    required: true
    type: string

outputs:
  should_run:
    value: ${{ steps.filter.outputs.should_run }}

runs:
  using: "composite"
  steps:
    - name: Detect changed files and compute condition
      id: filter
      shell: bash
      run: |
        set -eux
        # Exit early if this is main@domjudge/domjudge-packaging as
        # we have another workflow to run
        if [[ "${GITHUB_EVENT_NAME}" == "push" ]] &&
           [[ "${GITHUB_REPOSITORY}" == "DOMjudge/domjudge-packaging" ]] &&
           [[ "${GITHUB_REF_NAME}" == "main" ]]; then
          echo "should_run=false" >> $GITHUB_OUTPUT
          exit 0
        fi
        OREF="failure"
        CREF="failure"
        # Hardcode the organization and target branch to us
        # Alternative is to use:
        # - "${{ github.event.pull_request.base.repo.clone_url }}"
        # - "${{ github.event.pull_request.base.ref }}"
        # - "${{ github.event.repository.default_branch }}"
        # For more info see: `cat "$GITHUB_EVENT_PATH"
        if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
          OREF=$(jq -r '.pull_request.base.ref' "$GITHUB_EVENT_PATH")
          CREF=$(jq -r '.pull_request.head.ref' "$GITHUB_EVENT_PATH")
          ORG_CLONE=$(jq -r '.pull_request.base.repo.clone_url' "$GITHUB_EVENT_PATH")
          CONTRIB_CLONE=$(jq -r '.pull_request.head.repo.clone_url' "$GITHUB_EVENT_PATH")
        elif [[ "${GITHUB_EVENT_NAME}" == "merge_group" ]]; then
          # We might trigger twice here, both for the push#gh-readonly-queue & merge_group
          # if we want to prevent this we could do something like:
          # if [[ "${GITHUB_EVENT_NAME}" == "push" ]] &&
          #    [[ "${GITHUB_REPOSITORY}" == "DOMjudge/domjudge-packaging" ]] &&
          #    [[ "${GITHUB_REF_NAME}" == *gh-readonly-queue* ]]; then
          #   echo "should_run=false" >> $GITHUB_OUTPUT
          #   exit 0
          # fi
          OTMP=$(jq -r '.merge_group.base_ref' "$GITHUB_EVENT_PATH")
          CTMP=$(jq -r '.merge_group.head_ref' "$GITHUB_EVENT_PATH")
          OREF="${OTMP##refs\/heads\/}"
          CREF="${CTMP##refs\/heads\/}"
          ORG_CLONE=$(jq -r '.repository.clone_url' "$GITHUB_EVENT_PATH")
          CONTRIB_CLONE=$(jq -r '.repository.clone_url' "$GITHUB_EVENT_PATH")
        elif [[ "${GITHUB_EVENT_NAME}" == "push" ]]; then
          TMP="$( jq -r '.ref' "$GITHUB_EVENT_PATH")"
          OREF="$( jq -r '.repository.default_branch' "$GITHUB_EVENT_PATH" )"
          CREF="${TMP##refs\/heads\/}"
          ORG_CLONE=$(jq -r '.repository.clone_url' "$GITHUB_EVENT_PATH")
          CONTRIB_CLONE=$(jq -r '.repository.clone_url' "$GITHUB_EVENT_PATH")
        fi
        git remote add organization "$ORG_CLONE"
        git remote add contributor  "$CONTRIB_CLONE"
        git fetch organization
        git fetch contributor
        CHANGED=$(git diff --name-only "organization/$OREF" "contributor/$CREF")
        echo "changed_files: $CHANGED"
        for FILE in ${{ inputs.trigger-files }}; do
          if echo "$CHANGED" | grep -q "^${FILE}"; then
            echo "should_run=true" >> $GITHUB_OUTPUT
            exit 0
          fi
        done
        # None of the interesting files changed
        echo "should_run=false" >> $GITHUB_OUTPUT
