#!/bin/bash
# This script can be used to perform multiple tasks specifically
# on DOMjudge live USB instances. It must be run as root.
#
# Note that this script assumes that the default database credentials
# settings dbname=domjudge and dbuser=domjudge_jury are unchanged.

set -e

error()
{
	echo "Error: $@"
	exit 1
}

[ `id -u` -eq 0 ] || error "this program must be run as root."

case "$1" in
	rootpass)
		echo "Updating system root password..."
		passwd

		echo "Updating MySQL root password..."
		read -es -p "Enter new MySQL password: "  PASS1 ; echo
		read -es -p "Retype new MySQL password: " PASS2 ; echo
		[ "x$PASS1" = "x$PASS2" ] || error "passwords do not match."
		# Use Debian administrative credentials to login to the MySQL server.
		/usr/bin/mysql --defaults-file=/etc/mysql/debian.cnf mysql <<EOF
UPDATE user SET password=PASSWORD('$PASS1') WHERE user='root';
FLUSH PRIVILEGES;
EOF
		echo "MySQL root password updated."

		mv /etc/domjudge-default-passwords{,-disabled}

		cat <<EOF

You might also want to modify the default passwords in

  /etc/domjudge/htpasswd-{jury,plugin}

These two files contain credentials for the DOMjudge jury and plugin
web-interfaces, respectively. The jury interface has users 'admin' and
'jury' preconfigured, while the plugin interface has 'jury' and
'public'. The passwords are equal to the usernames. Edit these files
to remove these, and use e.g. the following command to add new users:

  htpasswd -m /etc/domjudge/htpasswd-jury <new-user>


Furthermore, the files

  /etc/domjudge/{domserver,judgedaemon}.dbconfig.php

contain the DOMjudge database user password. These are for internal
use only, and were generated on first boot of this image. They can be
regenerated with

  $0 genpass

This also updates the files /etc/dbconfig-common/domjudge-*.conf.
Propagate these passwords to any judgehosts with the command

  $0 syncjudge <judgehost>

to allow each judgehost to access the database on this host.

EOF
		;;

	genpass)
		echo "Generating new DOMjudge database credentials..."
		PW=`head -c12 /dev/urandom | base64 | head -c16 | tr '/+' 'Aa'`

		for f in /etc/dbconfig-common/domjudge-{domserver,judgehost}.conf ; do
			sed -i -e "s/^\(dbc_dbpass\)=.*/\1='$PW'/" \
			       -e "s/^\(dbc_dbserver\)=.*/\1=''/" $f
		done

		# Generate new DOMjudge include snippets from dbconfig:
		dbconfig-generate-include -f php -O root:www-data -m 0640 \
			/etc/dbconfig-common/domjudge-domserver.conf \
			/etc/domjudge/domserver.dbconfig.php
		dbconfig-generate-include -f php -O root:domjudge -m 0640 \
			/etc/dbconfig-common/domjudge-judgehost.conf \
			/etc/domjudge/judgedaemon.dbconfig.php

		# Use Debian administrative credentials to login to the MySQL server.
		/usr/bin/mysql --defaults-file=/etc/mysql/debian.cnf mysql <<EOF
UPDATE user SET password=PASSWORD('$PW') WHERE user='$USR';
FLUSH PRIVILEGES;
EOF

		cat <<EOF
DOMjudge database passwords updated.

You may also want to propagate these changes to any other judgehosts.

EOF
		;;

	syncjudge-remote)
		echo "Synchronizing passwords on '$HOSTNAME' to DB host '$3'..."

		sed -i -e "s/^\(dbc_dbpass\)=.*/\1='$2'/" \
		       -e "s/^\(dbc_dbserver\)=.*/\1='$3'/" \
			/etc/dbconfig-common/domjudge-judgehost.conf

		# Generate new DOMjudge include snippet from dbconfig:
		dbconfig-generate-include -f php -O root:domjudge -m 0640 \
			/etc/dbconfig-common/domjudge-judgehost.conf \
			/etc/domjudge/judgedaemon.dbconfig.php

		# Restart judgedaemon on remote judgehost:
		/etc/init.d/domjudge-judgehost stop || true
		/etc/init.d/domjudge-judgehost start
		;;

	syncjudge)
		JUDGEHOST="$2"
		[ -z "$JUDGEHOST" ] && error "required argument <judgehost> missing."

		echo "Synchronizing judgehost '$JUDGEHOST'..."

		PW=`grep '^dbc_dbpass=' /etc/dbconfig-common/domjudge-domserver.conf | \
			sed "s/^dbc_dbpass='\(.*\)'/\1/"`

		# Determine our resolvable hostname:
		ADDR=`/sbin/ip addr show eth0 | grep 'inet ' | sed 's/.*inet \([0-9\.]*\).*/\1/'`
		HOST=`dig +short -x $ADDR`
		HOST=${HOST:-$ADDR}

		# First make sure that remote hosts can connect to MySQL:
		/usr/bin/mysql --defaults-file=/etc/mysql/debian.cnf mysql <<EOF
UPDATE db SET host='%' WHERE db='domjudge';
UPDATE user SET host='%' WHERE user='domjudge_jury';
FLUSH PRIVILEGES;
EOF

		# Now update the DB credentials on the judgehost:
		ssh "$JUDGEHOST" "dj-live syncjudge-remote '$PW' '$HOST'"

		echo "Database information synchronized to '$JUDGEHOST'."
		;;

	upgrade)
		apt-get update
		apt-get dist-upgrade -y
		apt-get clean
		dj_upgrade_chroot
		;;

     *|help)
     cat <<EOF
Usage: $0 <command> [argument]...

Commands:
  rootpass    set system and MySQL database root passwords
  genpass     (re)generate DOMjudge DB user passwords
  syncjudge   synchronize DB information to a judgehost
  upgrade     install system (security) updates
  help        display this usage information

The 'syncjudge' command must be called with a resolvable judgehost
hostname as argument. The relevant data is synchronized over SSH.

EOF
	 exit 0
	 ;;

esac
