#!/usr/bin/php -q
<?php

require('/usr/share/domjudge/lib/vendor/mustangostang/spyc/Spyc.php');
require('/etc/domjudge/domserver.dbconfig.php');

$secret = bin2hex(random_bytes(32));

$yaml = [
    'parameters' => [
        'database_host' => $dbserver,
        'database_port' => $dbport,
        'database_name' => $dbname,
        'database_user' => $dbuser,
        'database_password' => $dbpass,
	'mailer_transport' => 'smtp',
	'mailer_host' => '127.0.0.1',
	'mailer_user' => '~',
	'mailer_password' => '~',
        'secret' => $secret
     ] ];


print Spyc::YAMLDump($yaml);
