#!/usr/bin/php -q
<?php

$ADMINPWFILE = "/etc/domjudge/initial_admin_password.secret";

if(file_exists($ADMINPWFILE)) {
    echo "$ADMINPWFILE exists, not doing anything.";
    exit(0);
}

touch($ADMINPWFILE);
chmod($ADMINPWFILE, 600);
echo `/etc/domjudge/genadminpassword > $ADMINPWFILE`;

$adminpw = trim(file_get_contents($ADMINPWFILE));

require('/etc/domjudge/domserver.dbconfig.php');
$link = mysqli_connect($dbserver, $dbuser, $dbpass, $dbname, $dbport);
echo mysqli_error($link);
mysqli_query($link, 'UPDATE user SET password = "' . password_hash($adminpw, PASSWORD_DEFAULT) . '" WHERE username = "admin";');
echo mysqli_error($link);
mysqli_close($link);

echo "\n\nInitial admin password set and written to $ADMINPWFILE\n\n";
