version: '3'

services:
  mariadb:
    image: docker.io/mariadb
    hostname: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=domjudge
      - MYSQL_USER=domjudge
      - MYSQL_PASSWORD=djpw
      - MYSQL_DATABASE=domjudge
    ports:
      - 13306:3306
    command: --max-connections=1000 --max-allowed-packet=512M
    volumes:
      - /var/lib/mysql
  domjudge:
    image: docker.io/domjudge/domserver
    hostname: domserver
    environment:
      - MYSQL_ROOT_PASSWORD=domjudge
      - MYSQL_USER=domjudge
      - MYSQL_PASSWORD=djpw
      - MYSQL_DATABASE=domjudge
      - MYSQL_HOST=mariadb
    ports:
      - 12345:80
# When using the Traefik reverse proxy container, uncomment the lines below.
#     labels:
#       - traefik.enable=true
#       - traefik.http.services.domjudge.loadbalancer.server.port=80
#       - traefik.http.routers.domjudge.rule=Host(`domjudge.example.com`)
#       - traefik.http.routers.domjudge.entrypoints=web
#       - traefik.http.routers.domjudgesecure.rule=Host(`domjudge.example.com`)
#       - traefik.http.routers.domjudgesecure.entrypoints=websecure
#       - traefik.http.routers.domjudgesecure.tls=true
#       - traefik.http.routers.domjudgesecure.tls.certresolver=myresolver
#       - traefik.docker.network=proxy_network
#     networks:
#       - default
#       - proxy_network
# networks:
#   proxy_network:
#     external: true
