#! /bin/sh -e

if [ -d /var/lib/domjudge/javachroot/proc ]; then
	umount /var/lib/domjudge/javachroot/proc || true
fi
if [ -d /var/lib/domjudge/javachroot.new/proc ]; then
	umount /var/lib/domjudge/javachroot.new/proc || true
fi

if [ -f /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
fi

if [ "$1" = "purge" ]; then
	rm -f /var/log/domjudge/judge.*.log
fi


#DEBHELPER#

exit 0
