#!/bin/bash
# This script can be used to perform multiple tasks specifically
# on DOMjudge-live image instances. It must be run as root.
#
# Note that this script assumes that the default database credentials
# settings dbname=domjudge and dbuser=domjudge_sql are unchanged.

set -e

error()
{
	echo "Error: $@"
	exit 1
}

[ `id -u` -eq 0 ] || error "this program must be run as root."

case "$1" in
	rootpass)
		echo "Updating system root password..."
		passwd

		echo "Updating MySQL root password..."
		read -es -p "Enter new MySQL password: "  PASS1 ; echo
		read -es -p "Retype new MySQL password: " PASS2 ; echo
		[ "x$PASS1" = "x$PASS2" ] || error "passwords do not match."
		# Use Debian administrative credentials to login to the MySQL server.
		/usr/bin/mysql --defaults-file=/etc/mysql/debian.cnf mysql <<EOF
UPDATE user SET password=PASSWORD('$PASS1') WHERE user='root';
FLUSH PRIVILEGES;
EOF
		echo "MySQL root password updated."

		rm /etc/issue
		ln -s /etc/issue.djlive /etc/issue

		cat <<EOF

You might also want to modify the default passwords for the web interfaces.
The jury interface has user 'admin' with password 'admin' preconfigured.
This can be changed in the web interface.

Furthermore, the files

  /etc/domjudge/domserver.dbconfig.php
  /etc/domjudge/restapi.secret

contain the DOMjudge database user and REST API passwords, respectively.
These are for internal use only, and were generated on first boot of this
image. They can be regenerated with

  $0 genpass

This also updates the file /etc/dbconfig-common/domjudge-domserver.conf.
The file /etc/domjudge/restapi.secret must be copied to any other judgehost
machines used, and the URL adapted to point to the main DOMjudge server.

EOF
		;;

	genpass)
		printf "Generating new DOMjudge database credentials..."
		PW=$(head -c12 /dev/urandom | base64 | head -c16 | tr '/+' 'Aa')

		sed -i -e "s/^\(dbc_dbpass\)=.*/\1='$PW'/" \
		       -e "s/^\(dbc_dbserver\)=.*/\1=''/" \
		    /etc/dbconfig-common/domjudge-domserver.conf

		# Generate new DOMjudge include snippet from dbconfig:
		dbconfig-generate-include -f php -O root:www-data -m 0640 \
			/etc/dbconfig-common/domjudge-domserver.conf \
			/etc/domjudge/domserver.dbconfig.php

		# Use Debian administrative credentials to login to the MySQL server.
		/usr/bin/mysql --defaults-file=/etc/mysql/debian.cnf mysql <<EOF
UPDATE user SET password=PASSWORD('$PW') WHERE user='domjudge_sql';
FLUSH PRIVILEGES;
EOF

		echo " done."

		echo "Generating new DOMjudge REST API password..."

		# Generate REST API password and set it for judgehost user:
		/etc/domjudge/genrestapicredentials > /etc/domjudge/restapi.secret

		RESTPW=$(tail -n1 /etc/domjudge/restapi.secret | sed 's/.*[[:space:]]//')

		# NOTE: the hash function and cost below have to be kept
		# synchronised with those used in the code!
		PWHASH=$(htpasswd -nbB -C 10 foouser "$RESTPW" | sed 's/^foouser://')

		/usr/bin/mysql --defaults-file=/etc/mysql/debian.cnf domjudge <<EOF
UPDATE user SET password='$PWHASH' WHERE username='judgehost';
EOF

		echo " done."

		;;

	upgrade)
		apt-get update
		apt-get dist-upgrade -y
		apt-get clean
		dj_upgrade_chroot
		;;

     *|help)
     cat <<EOF
Usage: $0 <command> [argument]...

Commands:
  rootpass    set system and MySQL database root passwords
  genpass     (re)generate DOMjudge DB user and REST API passwords
  upgrade     install system (security) updates
  help        display this usage information

EOF
	 exit 0
	 ;;

esac
