#!/bin/bash
# This script can be used to perform multiple tasks specifically
# on DOMjudge-live image instances. It must be run as root.
#
# Note that this script assumes that the default database credentials
# settings dbname=domjudge and dbuser=domjudge_sql are unchanged.

set -e

error()
{
	echo "Error: $*"
	exit 1
}

# NOTE: the hash function and cost below have to be kept synchronised
# with those used in DOMjudge code!
dj_pwhash()
{
	[ -n "$1" ] || error "missing password argument to dj_pwhash."
	htpasswd -nbB -C 10 foouser "$1" | sed 's/^foouser://'
}

[ "$(id -u)" -eq 0 ] || error "this program must be run as root."

case "$1" in
	rootpass)
		echo "Updating system root password..."
		passwd

		rm /etc/issue
		ln -s /etc/issue.djlive /etc/issue

		cat <<EOF

You might also want to modify the default password for the web interface.
The admin user has password 'admin' preconfigured. This can be changed in
the web interface, or by running

  $0 adminpass

Furthermore, the files

  /etc/domjudge/domserver.dbconfig.php
  /etc/domjudge/restapi.secret

contain the DOMjudge database user and REST API passwords, respectively.
These are for internal use only, and were generated on first boot of this
image. If needed, they can be regenerated with

  $0 dbapipass

This also updates the files /etc/dbconfig-common/domjudge-domserver.conf
and /usr/share/domjudge/webapp/app/config/parameters.yml.
The file /etc/domjudge/restapi.secret must be copied to any other judgehost
machines used, and the URL adapted to point to the main DOMjudge server.

EOF
		;;

	adminpass)
		[ -n "$2" ] && PASS="$2"

		echo "Updating DOMjudge web interface admin user password..."
		if [ -z "$PASS" ]; then
			read -esr -p "Enter new admin user password: "  PASS1 ; echo
			read -esr -p "Retype new admin user password: " PASS2 ; echo
			[ "$PASS1" = "$PASS2" ] || error "passwords do not match."
			PASS="$PASS1"
		fi

		# NOTE: the hash function and cost below have to be kept
		# synchronised with those used in the code!
		PWHASH=$(dj_pwhash "$PASS")

		mysql domjudge <<EOF
UPDATE user SET password='$PWHASH' WHERE username='admin';
EOF

		echo " done."

		;;

	dbapipass)
		printf "Generating new DOMjudge database credentials..."
		PW=$(head -c12 /dev/urandom | base64 | head -c16 | tr '/+' 'Aa')

		sed -i -e "s/^\(dbc_dbpass\)=.*/\1='$PW'/" \
		       -e "s/^\(dbc_dbserver\)=.*/\1=''/" \
		    /etc/dbconfig-common/domjudge-domserver.conf

		sed -i -e "s/^\( *database_password:\).*/\1 $PW/" \
			/usr/share/domjudge/webapp/app/config/parameters.yml

		# Generate new DOMjudge include snippet from dbconfig:
		dbconfig-generate-include -f php -O root:www-data -m 0640 \
			/etc/dbconfig-common/domjudge-domserver.conf \
			/etc/domjudge/domserver.dbconfig.php

		# Use Debian administrative credentials to login to the MySQL server.
		mysql mysql <<EOF
UPDATE user SET password=PASSWORD('$PW') WHERE user='domjudge_sql';
FLUSH PRIVILEGES;
EOF

		# Remove Symfony cache, since it stores the password.
		rm -rf /var/cache/domjudge/prod

		echo " done."

		echo "Generating new DOMjudge REST API password..."

		# Generate REST API password and set it for judgehost user:
		/etc/domjudge/genrestapicredentials > /etc/domjudge/restapi.secret

		RESTPW=$(tail -n1 /etc/domjudge/restapi.secret | sed 's/.*[[:space:]]//')
		PWHASH=$(dj_pwhash "$RESTPW")

		mysql domjudge <<EOF
UPDATE user SET password='$PWHASH' WHERE username='judgehost';
EOF

		# Restart judgedaemon if it was meant to be running:
		service domjudge-judgehost status >/dev/null 2>&1
		exitcode=$?
		if [ $exitcode -le 1 ]; then
			service domjudge-judgehost restart
		fi

		echo " done."

		;;

	upgrade)
		apt-get update
		apt-get dist-upgrade -y
		apt-get clean
		dj_upgrade_chroot
		;;

    help|*)
     cat <<EOF
Usage: $0 <command> [argument]...

Commands:
  rootpass    set system root password
  dbapipass   (re)generate DOMjudge DB user and REST API passwords
  adminpass   set DOMjudge web interface admin user password
  upgrade     install system (security) updates
  help        display this usage information

EOF
	 exit 0
	 ;;

esac
