name: 'Build DOMjudge container(s) (PR)'

permissions:
  contents: read
  packages: write

on:
  merge_group:
    # We can't limit the files as below as this is a required check so should run
    # We exit early in case no relevant file changed
    types: [checks_requested]
  pull_request:
    branches:
      - main
  push:
    # We don't start the job if no relevant file changed
    paths:
      # This is an `either`, so any file listed here will trigger
      - docker/**
      - .github/workflows/build-domjudge-container-PR.yml

env:
  DOMJUDGE_VERSION: M.m.p

jobs:
  pr-domjudge:
    name: Build PR DOMjudge docker image(s)
    runs-on: ubuntu-latest
    outputs:
      dj-version: ${{ env.PR_TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Detect changed files and compute condition
        id: filter
        uses: ./.github/actions/helper-detect-changed-files
        with:
          trigger-files: "docker .github/workflows/build-domjudge-container-PR.yml .github/jobs/check-domjudge-container.sh"

      - name: Mark as skipped
        if: steps.filter.outputs.should_run == 'false'
        run: echo "Skip job, no important files changed"

      - name: Set up QEMU
        if: steps.filter.outputs.should_run == 'true'
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        if: steps.filter.outputs.should_run == 'true'
        uses: docker/setup-buildx-action@v4

      - name: Login to GitHub container registry
        if: steps.filter.outputs.should_run == 'true'
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: docker system prune -a -f
        if: steps.filter.outputs.should_run == 'true'

      - name: Get an unique tag for when people PR often
        if: steps.filter.outputs.should_run == 'true'
        run: |
          GHR=${{ github.ref }}
          GHA=${{ github.actor }}
          echo "PR_TAG=${GHR///}${GHA//[\]\[]/}" >> $GITHUB_ENV

      - name: If needed overwrite the DOMJUDGE_VERSION for this run
        if: steps.filter.outputs.should_run == 'true'
        run: |
          if [ ${{ env.DOMJUDGE_VERSION }} != "M.m.p" ]; then
            exit 0
          fi
          sudo apt-get update; sudo apt-get install -y jq curl
          set -x
            HUBURL="https://registry.hub.docker.com/v2/repositories/domjudge/domserver/tags"
            TAG=$(curl $HUBURL|jq '.results | map(select(.name != "bleeding")) | map(select(.name != "latest")) | sort_by(.name) | .[-1].name')
            DJ_TAG=${TAG//\"}
          set +x
          echo "DOMJUDGE_VERSION=$DJ_TAG" >> $GITHUB_ENV

      - name: Build the container
        if: steps.filter.outputs.should_run == 'true'
        run: |
          cd docker
          ./build.sh "${{ env.DOMJUDGE_VERSION }}" "${GITHUB_REPOSITORY_OWNER@L}"
          cd ../docker-chroot
          ./build.sh "${{ env.DOMJUDGE_VERSION }}" "${GITHUB_REPOSITORY_OWNER@L}"

      - name: Build and push
        if: steps.filter.outputs.should_run == 'true'
        run: |
          mkdir -p /tmp/images
          for IMG in domserver judgehost default-judgehost-chroot icpc-judgehost-chroot full-judgehost-chroot; do
            echo "::group::${IMG}"
            IMAGE_NAME="${GITHUB_REPOSITORY_OWNER@L}/${IMG}:${{ env.DOMJUDGE_VERSION }}"
            docker image tag "$IMAGE_NAME" ghcr.io/${GITHUB_REPOSITORY_OWNER@L}/$IMG:${{ env.PR_TAG }}
            docker image tag "$IMAGE_NAME" ${GITHUB_REPOSITORY_OWNER@L}/$IMG:${{ env.PR_TAG }}
            if "$IMG" = "domserver" || "$IMG" = "judgehost"; then
              docker save -o /tmp/images/${IMG}.tar ${GITHUB_REPOSITORY_OWNER@L}/$IMG:${{ env.PR_TAG }}
            done
            # Push fails for forks, and the pulled data should be the same as the 'docker save' above.
            docker push ghcr.io/${GITHUB_REPOSITORY_OWNER@L}/$IMG:${{ env.PR_TAG }} || true
            echo "::endgroup::"
          done

      - run: docker image list
        if: steps.filter.outputs.should_run == 'true'

      - name: Upload image artifact for 'container-check' job
        if: steps.filter.outputs.should_run == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: pr-docker-images
          path: /tmp/images
          retention-days: 2

  container-check:
    name: Test PR DOMjudge docker image(s)
    runs-on: ubuntu-latest
    needs: pr-domjudge
    strategy:
      matrix:
        database: ['mariadb', 'mysql']
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download built image
        uses: actions/download-artifact@v4
        with:
          name: pr-docker-images
          path: /tmp/images

      - name: Load image into Docker
        run: |
          # Todo, test the actual chroots also
          for IMG in domserver judgehost; do
            docker load -i /tmp/images/${IMG}.tar
          done

      - name: Check the created domserver/judgehost containers
        run: .github/jobs/check-domjudge-container.sh ${{ needs.pr-domjudge.outputs.dj-version }} ${GITHUB_REPOSITORY_OWNER@L} ${{ matrix.database }}

      - name: Collect docker logs on failure
        if: ${{ !cancelled() }}
        uses: jwalton/gh-docker-logs@v2
        with:
          dest: '/tmp/docker-logs'

      - name: Upload all logs
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: Logs-${{ matrix.database }}
          path: /tmp/docker-logs
